/**
 * Kabadiwala Lite — Collector Earnings & Saved Slips Ledger
 * Stores and displays digital scrap slips generated by door-to-door collectors,
 * tracking daily collection weight and estimated earnings.
 */

import { formatCurrency, formatWeight, formatDate, showToast } from '../utils.js';
import { i18n } from '../i18n.js';
import QRCode from 'qrcode';

const STORAGE_KEY = 'kw_collector_slips';

const DEFAULT_DEMO_SLIPS = [
  {
    id: 'SLIP-2026-DL-8821',
    category: 'PCB',
    weight: 6.5,
    rate: 520,
    estimatedValue: 3380,
    gpsText: 'Mayapuri Industrial Area, New Delhi',
    latitude: 28.628,
    longitude: 77.123,
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    customerPhone: '+91 98711 00234'
  },
  {
    id: 'SLIP-2026-DL-8820',
    category: 'Cable',
    weight: 12.0,
    rate: 380,
    estimatedValue: 4560,
    gpsText: 'Shadipur Depot, New Delhi',
    latitude: 28.651,
    longitude: 77.158,
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    customerPhone: '+91 98109 44321'
  },
  {
    id: 'SLIP-2026-DL-8819',
    category: 'Battery',
    weight: 15.0,
    rate: 110,
    estimatedValue: 1650,
    gpsText: 'Kirti Nagar Market, New Delhi',
    latitude: 28.655,
    longitude: 77.135,
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    customerPhone: ''
  }
];

export function getCollectorSlips() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(DEFAULT_DEMO_SLIPS));
      return DEFAULT_DEMO_SLIPS;
    }
    return JSON.parse(raw);
  } catch (e) {
    console.error('Failed to parse collector slips:', e);
    return DEFAULT_DEMO_SLIPS;
  }
}

export function saveCollectorSlip(slip) {
  try {
    const slips = getCollectorSlips();
    slips.unshift(slip);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(slips));
    return slips;
  } catch (e) {
    console.error('Failed to save slip:', e);
    return [];
  }
}

export function deleteCollectorSlip(slipId) {
  try {
    const slips = getCollectorSlips().filter(s => s.id !== slipId);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(slips));
    return slips;
  } catch (e) {
    return [];
  }
}

export function renderCollectorLedgerView(container, navigateTo) {
  const slips = getCollectorSlips();
  const t = (k, p) => i18n.t(k, p);

  // Compute daily totals
  const totalWeight = slips.reduce((sum, s) => sum + (Number(s.weight) || 0), 0);
  const totalEstimatedValue = slips.reduce((sum, s) => sum + (Number(s.estimatedValue) || 0), 0);

  container.innerHTML = `
    <div class="view-transition">
      <!-- Header -->
      <div style="margin-bottom: var(--space-md);">
        <span style="font-size: 0.75rem; font-weight: 700; color: #38bdf8; text-transform: uppercase;">
          📒 ${t('ledgerTab')}
        </span>
        <h2 style="font-size: 1.35rem; font-weight: 800; color: var(--text-main); margin-top: 2px;">
          My Slips &amp; Daily Earnings
        </h2>
        <p style="font-size: 0.8rem; color: var(--text-secondary);">
          Your digital record of collected scrap &amp; estimated fair value
        </p>
      </div>

      <!-- Daily Summary Card -->
      <div class="card" style="background: linear-gradient(135deg, rgba(16, 185, 129, 0.15), rgba(14, 165, 233, 0.08)); border-color: rgba(52, 211, 153, 0.35); padding: 16px; margin-bottom: var(--space-md);">
        <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 12px;">
          <div>
            <div style="font-size: 0.75rem; font-weight: 700; color: #a7f3d0; text-transform: uppercase;">
              Today's Estimated Earnings
            </div>
            <div style="font-size: 2rem; font-weight: 900; color: #34d399; font-family: 'JetBrains Mono', monospace; margin-top: 2px;">
              ${formatCurrency(totalEstimatedValue)}
            </div>
          </div>
          <button class="btn btn-sm btn-outline" id="speakLedgerBtn" title="Listen / सुनें">
            <span>🔊 Listen</span>
          </button>
        </div>

        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 10px; padding-top: 12px; border-top: 1px solid rgba(255,255,255,0.08);">
          <div>
            <span style="font-size: 0.72rem; color: #94a3b8;">Total Scrap Weight</span>
            <div style="font-size: 1.1rem; font-weight: 800; color: #f8fafc;">
              ${formatWeight(totalWeight)}
            </div>
          </div>
          <div>
            <span style="font-size: 0.72rem; color: #94a3b8;">Saved Slips</span>
            <div style="font-size: 1.1rem; font-weight: 800; color: #f8fafc;">
              ${slips.length} ${slips.length === 1 ? 'slip' : 'slips'}
            </div>
          </div>
        </div>
      </div>

      <!-- Quick Action: Scan More Scrap -->
      <div style="margin-bottom: var(--space-md);">
        <button class="btn btn-primary" id="scanMoreBtn" style="width: 100%; border-radius: 14px; padding: 12px; font-weight: 700;">
          <span>📷 Scan &amp; Value More Scrap</span>
        </button>
      </div>

      <!-- Slips List -->
      <div>
        <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 10px;">
          <h3 style="font-size: 0.95rem; font-weight: 700; color: var(--text-main);">
            Collection Slips (${slips.length})
          </h3>
          ${slips.length > 0 ? `
            <button class="btn btn-sm btn-outline" id="clearAllSlipsBtn" style="color: #f87171; border-color: rgba(248,113,113,0.3); font-size: 0.72rem;">
              Clear All
            </button>
          ` : ''}
        </div>

        ${slips.length === 0 ? `
          <div class="card" style="text-align: center; padding: 30px 20px;">
            <div style="font-size: 2.5rem; margin-bottom: 10px;">📋</div>
            <h4 style="font-size: 1rem; font-weight: 700; color: #e2e8f0; margin-bottom: 6px;">No Slips Saved Yet</h4>
            <p style="font-size: 0.8rem; color: #94a3b8; max-width: 280px; margin: 0 auto 16px;">
              Snap a scrap photo, enter approximate weight, and tap "Save Digital Scrap Slip" to build your earnings record.
            </p>
            <button class="btn btn-primary btn-sm" id="emptyScanBtn">
              Start Scanning
            </button>
          </div>
        ` : `
          <div style="display: flex; flex-direction: column; gap: 10px;">
            ${slips.map(s => `
              <div class="card slip-card" data-id="${s.id}" style="padding: 14px 16px;">
                <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 8px;">
                  <div style="display: flex; align-items: center; gap: 10px;">
                    <span style="font-size: 1.8rem;">${s.icon || '📦'}</span>
                    <div>
                      <h4 style="font-size: 0.95rem; font-weight: 700; color: #f8fafc; margin: 0;">
                        ${i18n.getCategoryName(s.category)}
                      </h4>
                      <div style="font-size: 0.74rem; color: #94a3b8;">
                        ${formatDate(s.createdAt)} • ${s.weight} kg @ ₹${s.rate}/kg
                      </div>
                    </div>
                  </div>
                  <div style="text-align: right;">
                    <div style="font-size: 1.15rem; font-weight: 800; color: #34d399; font-family: 'JetBrains Mono', monospace;">
                      ${formatCurrency(s.estimatedValue)}
                    </div>
                    <span class="badge badge-info" style="font-size: 0.65rem;">
                      ${s.gpsText ? `📍 ${s.gpsText}` : 'Field Record'}
                    </span>
                  </div>
                </div>

                <!-- Footer Actions -->
                <div style="display: flex; justify-content: space-between; align-items: center; padding-top: 8px; border-top: 1px solid rgba(255,255,255,0.06);">
                  <div style="font-size: 0.72rem; color: var(--text-muted); font-family: 'JetBrains Mono', monospace;">
                    ID: ${s.id.slice(0, 8)}
                  </div>
                  <div style="display: flex; gap: 6px;">
                    <button class="btn btn-sm btn-outline view-slip-qr-btn" data-id="${s.id}">
                      <span>📱 View QR Slip</span>
                    </button>
                    <button class="btn btn-sm btn-outline delete-slip-btn" data-id="${s.id}" style="color: #f87171; padding: 4px 8px;">
                      ✕
                    </button>
                  </div>
                </div>
              </div>
            `).join('')}
          </div>
        `}
      </div>
    </div>
  `;

  // Bind Buttons
  container.querySelector('#scanMoreBtn')?.addEventListener('click', () => navigateTo('collector-lite'));
  container.querySelector('#emptyScanBtn')?.addEventListener('click', () => navigateTo('collector-lite'));

  // Voice narration of earnings
  container.querySelector('#speakLedgerBtn')?.addEventListener('click', (e) => {
    const btn = e.currentTarget;
    const lang = i18n.getLang();
    
    const text = lang === 'hi'
      ? `आज आपने ${slips.length} पर्चियों में ${totalWeight.toFixed(1)} किलो ई-कचरा कबाड़ इकट्ठा किया है, जिसकी कुल अनुमानित कीमत ${totalEstimatedValue} रुपये है।`
      : `Today you have collected ${totalWeight.toFixed(1)} kilograms of e-waste scrap across ${slips.length} slips, with total estimated fair value of ${totalEstimatedValue} rupees.`;
      
    btn.classList.add('pulse-anim');
    i18n.speak(text, {
      onEnd: () => btn.classList.remove('pulse-anim'),
      onError: () => btn.classList.remove('pulse-anim')
    });
  });

  // Clear all
  container.querySelector('#clearAllSlipsBtn')?.addEventListener('click', () => {
    if (confirm('Clear all saved slips?')) {
      localStorage.removeItem(STORAGE_KEY);
      renderCollectorLedgerView(container, navigateTo);
      showToast('All slips cleared', 'info');
    }
  });

  // Delete individual slip
  container.querySelectorAll('.delete-slip-btn').forEach(btn => {
    btn.addEventListener('click', (e) => {
      e.stopPropagation();
      const id = btn.getAttribute('data-id');
      deleteCollectorSlip(id);
      renderCollectorLedgerView(container, navigateTo);
      showToast('Slip removed', 'info');
    });
  });

  // View QR Slip Modal
  container.querySelectorAll('.view-slip-qr-btn').forEach(btn => {
    btn.addEventListener('click', async (e) => {
      e.stopPropagation();
      const id = btn.getAttribute('data-id');
      const slip = slips.find(s => s.id === id);
      if (slip) {
        showSlipQrModal(slip);
      }
    });
  });
}

/**
 * Renders a full Digital Scrap Slip Modal with Scannable QR & Tamper-Proof Metadata
 */
export async function showSlipQrModal(slip) {
  let modal = document.getElementById('kwSlipModal');
  if (modal) modal.remove();

  modal = document.createElement('div');
  modal.id = 'kwSlipModal';
  modal.className = 'lang-modal-backdrop';

  // Generate QR Code data URL
  let qrDataUrl = '';
  try {
    // Encodes pure Slip ID and verifiable verification payload
    const qrPayload = JSON.stringify({
      slipId: slip.id,
      category: slip.category,
      weight: slip.weight,
      estValue: slip.estimatedValue,
      gps: slip.gpsText || 'Stamped'
    });
    qrDataUrl = await QRCode.toDataURL(qrPayload, {
      width: 220,
      margin: 2,
      color: { dark: '#020617', light: '#ffffff' }
    });
  } catch (err) {
    console.error('QR generation failed:', err);
  }

  modal.innerHTML = `
    <div class="lang-modal-card" style="text-align: center; padding: 24px 20px;">
      <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px;">
        <span class="badge badge-success">✓ Digital Scrap Slip</span>
        <button class="btn btn-sm btn-outline" id="closeSlipModal">✕</button>
      </div>

      <!-- Receipt Header -->
      <div style="margin-bottom: 14px;">
        <div style="font-size: 1.8rem; margin-bottom: 2px;">${slip.icon || '📦'}</div>
        <h3 style="font-size: 1.2rem; font-weight: 800; color: #f8fafc; margin: 0;">
          ${i18n.getCategoryName(slip.category)}
        </h3>
        <p style="font-size: 0.78rem; color: #94a3b8; margin-top: 2px;">
          Created: ${formatDate(slip.createdAt)}
        </p>
      </div>

      <!-- QR Code Box -->
      <div style="background: #ffffff; padding: 12px; border-radius: 16px; display: inline-block; box-shadow: 0 4px 20px rgba(0,0,0,0.4); margin-bottom: 14px;">
        <img src="${qrDataUrl}" style="width: 180px; height: 180px; display: block;" alt="Scrap Slip QR" />
        <div style="font-family: 'JetBrains Mono', monospace; font-size: 0.7rem; color: #0f172a; font-weight: 700; margin-top: 4px;">
          SLIP-${slip.id.slice(0, 8).toUpperCase()}
        </div>
      </div>

      <!-- Key Details Grid -->
      <div style="background: rgba(30, 41, 59, 0.6); border: 1px solid rgba(148, 163, 184, 0.2); border-radius: 14px; padding: 12px; text-align: left; margin-bottom: 14px;">
        <div style="display: flex; justify-content: space-between; margin-bottom: 6px; font-size: 0.82rem;">
          <span style="color: #94a3b8;">Declared Weight:</span>
          <strong style="color: #f8fafc;">${slip.weight} kg</strong>
        </div>
        <div style="display: flex; justify-content: space-between; margin-bottom: 6px; font-size: 0.82rem;">
          <span style="color: #94a3b8;">Estimated Fair Value:</span>
          <strong style="color: #34d399; font-family: 'JetBrains Mono', monospace;">${formatCurrency(slip.estimatedValue)}</strong>
        </div>
        <div style="display: flex; justify-content: space-between; font-size: 0.78rem;">
          <span style="color: #94a3b8;">GPS Stamped:</span>
          <strong style="color: #38bdf8;">📍 ${slip.gpsText || 'Field Stamped'}</strong>
        </div>
      </div>

      <div style="font-size: 0.74rem; color: #94a3b8; line-height: 1.3;">
        Show this QR code to your authorized scrap dealer or recycler at the weighbridge.
      </div>
    </div>
  `;

  document.body.appendChild(modal);

  modal.querySelector('#closeSlipModal').addEventListener('click', () => modal.remove());
  modal.addEventListener('click', (e) => {
    if (e.target === modal) modal.remove();
  });
}
